import { defineStore } from 'pinia';
import { reactive } from 'vue';

interface Animal {
    id: number;
    image: string;
    name: string;
    family: string;
    gener: string;
    origin: string;
    date: string;
    tipe: string;
    title: string;
}

export const useAnimalsStore = defineStore('animals', () => {
    const animals = reactive<Animal[]>([
        {
            id: 1,
            image: './src/assets/img/chacales.jpg',
            name: 'Chacal',
            family: 'Canidae',
            gener: 'Hembra',
            origin: 'África',
            date: 'date',
            tipe: 'Canis',
            title: 'Chacal',
        },
        {
            id: 2,
            image: './src/assets/img/chita.jpg',
            name: 'Chita',
            family: 'Felidae',
            gener: 'macho',
            origin: 'África y Asia',
            date: 'date',
            tipe: 'Acinonyx',
            title: 'Chita',
        },
        {
            id: 3,
            image: './src/assets/img/cocodrilo.jpg',
            name: 'Cocodrilo',
            family: 'Reptil',
            gener: 'macho',
            origin: 'América Central y del Sur',
            date: 'date',
            tipe: 'Cocodylus',
            title: 'Cocodrilo',
        },
        {
            id: 4,
            image: './src/assets/img/comadreja2.jpg',
            name: 'Comadreja',
            family: 'Mustelidae',
            gener: 'macho',
            origin: 'Europa, Asia y África',
            date: 'date',
            tipe: 'Mustela',
            title: 'Comadreja',
        },
        {
            id: 5,
            image: './src/assets/img/conejo.jpg',
            name: 'Conejo',
            family: 'Leporidae',
            gener: 'macho',
            origin: 'América del Norte',
            date: 'date',
            tipe: 'Oryctolagus',
            title: 'Conejo',
        },
        {
            id: 6,
            image: './src/assets/img/coyote.jpg',
            name: 'Coyote',
            family: 'Canidae',
            gener: 'macho',
            origin: 'América del Norte',
            date: 'date',
            tipe: 'Canis',
            title: 'Coyote',
        },
        {
            id: 7,
            image: './src/assets/img/huron.jpg',
            name: 'Huron',
            family: 'Felidae',
            gener: 'Hembra',
            origin: 'Norteamérica',
            date: 'date',
            tipe: 'Lynx',
            title: 'Huron',
        },
        {
            id: 8,
            image: './src/assets/img/iguana.jpg',
            name: 'Iguana',
            family: 'Reptil',
            gener: 'Hembra',
            origin: 'América Central y del Sur',
            date: 'date',
            tipe: 'Iguanidae',
            title: 'Iguana',
        },
        {
            id: 9,
            image: './src/assets/img/leon.jpg',
            name: 'León',
            family: 'Felidae',
            gener: 'Hembra',
            origin: 'África, Asia y América.',
            date: 'date',
            tipe: 'Panthera',
            title: 'León',
        },
        {
            id: 10,
            image: './src/assets/img/leopardo.jpg',
            name: 'Leopardo',
            family: 'Felidae',
            gener: 'Hembra',
            origin: 'África y Asia',
            date: 'date',
            tipe: 'Panthera',
            title: 'Leopardo',
        },
        {
            id: 11,
            image: './src/assets/img/liebre.jpg',
            name: 'Liebre',
            family: 'Leporidae',
            gener: 'macho',
            origin: 'Mundial',
            date: 'date',
            tipe: 'Lepus',
            title: 'Liebre',
        },
        {
            id: 12,
            image: './src/assets/img/lince.jpg',
            name: 'Linces',
            family: 'Felidae',
            gener: 'macho',
            origin: 'Eurasia',
            date: 'date',
            tipe: 'Lynx',
            title: 'Linces',
        },
        {
            id: 13,
            image: './src/assets/img/nutria.jpg',
            name: 'Nutria',
            family: 'Myocastoridae',
            gener: 'macho',
            origin: 'Sudamérica',
            date: 'date',
            tipe: 'Myocastor',
            title: 'Nutria',
        },
        {
            id: 14,
            image: './src/assets/img/panda.jpg',
            name: 'Panda',
            family: 'Mustelidae',
            gener: 'macho',
            origin: 'Asia',
            date: 'date',
            tipe: 'Ailuropoda',
            title: 'Panda',
        },
        {
            id: 15,
            image: './src/assets/img/pantera.jpg',
            name: 'Pantera',
            family: 'Felidae',
            gener: 'macho',
            origin: 'África, Asia y América.jpg',
            date: 'date',
            tipe: 'Panthera',
            title: 'Pantera',
        },
        {
            id: 16,
            image: './src/assets/img/puma.jpg',
            name: 'Puma',
            family: 'Felidae',
            gener: 'macho',
            origin: 'América',
            date: 'date',
            tipe: 'Puma',
            title: 'Puma',
        },
        {
            id: 17,
            image: './src/assets/img/rataalmizclera.jpg',
            name: 'Rata Almizclera',
            family: 'Mustelidae',
            gener: 'macho',
            origin: 'América del Norte',
            date: 'date',
            tipe: 'Mus',
            title: 'Rata Almizclera',
        },
        {
            id: 18,
            image: './src/assets/img/serpienteanaconda.jpg',
            name: 'Serpiente Anaconda',
            family: 'Reptil',
            gener: 'femenino',
            origin: 'Sudamérica',
            date: 'date',
            tipe: 'Boidae',
            title: 'Anaconda',
        },
        {
            id: 19,
            image: './src/assets/img/serpientecascabel.jpg',
            name: 'Serpeinte Cascabel',
            family: 'Reptil',
            gener: 'macho',
            origin: 'América del Sur',
            date: 'date',
            tipe: 'Crotalus',
            title: 'Cascabel',
        },

        {
            id: 20,
            image: './src/assets/img/tejon.jpg',
            name: 'Tejón',
            family: 'Sciuridae',
            gener: 'Hembra',
            origin: 'Norteamérica',
            date: 'date',
            tipe: 'Tamias',
            title: 'Tejón',
        },
        {
            id: 21,
            image: './src/assets/img/tigre.jpg',
            name: 'Tigre',
            family: 'Felidae',
            gener: 'Hembra',
            origin: 'Asía',
            date: 'date',
            tipe: 'Panthera',
            title: 'Tigre',
        },
        {
            id: 22,
            image: './src/assets/img/tigredebengala.jpg',
            name: 'Tigre',
            family: 'Felidae',
            gener: 'Hembra',
            origin: 'India',
            date: 'date',
            tipe: 'Panthera',
            title: 'Tigre de Bengala',
        },
        {
            id: 23,
            image: './src/assets/img/tortugamarina.jpg',
            name: 'Tortuga',
            family: 'Reptil',
            gener: 'Hembra',
            origin: 'Mundo',
            date: 'date',
            tipe: 'Chelonia',
            title: 'Tortuga Marina',
        },
        {
            id: 24,
            image: './src/assets/img/yacare.jpg',
            name: 'Yacaré',
            family: 'Reptil',
            gener: 'Hembra',
            origin: 'América del Sur',
            date: 'date',
            tipe: 'Caiman',
            title: 'Yacaré',
        },
        {
            id: 25,
            image: './src/assets/img/zorro.jpg',
            name: 'Zorro',
            family: 'Canidae',
            gener: 'Hembra',
            origin: 'Europa y Asía',
            date: 'date',
            tipe: 'Vulpes',
            title: 'Zorro',
        },
        {
            id: 26,
            image: './src/assets/img/zorrodelasnieves.jpg',
            name: 'Zorro de las Nieves',
            family: 'Canidae',
            gener: 'Macho',
            origin: 'Artico',
            date: 'date',
            tipe: 'Vulpes',
            title: 'Zorro Nival',
        }
    ]);

    function addAnimal(newAnimal: Animal) {
        animals.push(newAnimal);
    }

    return {
        animals,
        addAnimal
    };
});